name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get saxon
        run: |
          curl -L https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-5/SaxonHE12-5J.zip -o SaxonHE12-5J.zip
          unzip SaxonHE12-5J.zip
      - name: ls3yi test
        run: |
          java -jar saxon-he-12.5.jar -xsl:page2tei-0.xsl -s:test/ls3yi/mets.xml -o:test/ls3yi/ls3yi_test.xml
          diff -w --normal test/ls3yi/ls3yi_test.xml test/ls3yi/ls3yi.xml
      - name: 8cd62 textblock + cbr-li test
        run: |
          java -jar saxon-he-12.5.jar -xsl:page2tei-0.xsl -s:test/8cd62_testament_textblock_cbr-li/mets.xml -o:test/8cd62_testament_textblock_cbr-li/testament_textblock_cbr-li_test.xml
          diff -w --normal test/8cd62_testament_textblock_cbr-li/testament_textblock_cbr-li_test.xml test/8cd62_testament_textblock_cbr-li/8cd62.xml
      - name: ifowu schuelerverz tables test
        run: |
          java -jar saxon-he-12.5.jar -xsl:page2tei-0.xsl -s:test/ifowu_schuelerverz_tables/mets.xml -o:test/ifowu_schuelerverz_tables/ifowu_schuelerverz_tables_test.xml
          diff -w --normal test/ifowu_schuelerverz_tables/ifowu_schuelerverz_tables_test.xml test/ifowu_schuelerverz_tables/ifowu.xml
      - name: marginalia (front, body, back) test
        run: |
          java -jar saxon-he-12.5.jar -xsl:page2tei-0.xsl -s:test/marginalia/mets.xml -o:test/marginalia/marginalia_test.xml
          diff -w --normal test/marginalia/marginalia_test.xml test/marginalia/marginalia.xml
      - name: marginalia (bottom and left) and table test
        run: |
          java -jar saxon-he-12.5.jar -xsl:page2tei-0.xsl -s:test/marginalia_table/mets.xml -o:test/marginalia_table/marginalia_table_test.xml
          diff -w --normal test/marginalia_table/marginalia_table_test.xml test/marginalia_table/marginalia_table.xml